os:
  - linux
sudo: false
addons:
  apt:
    packages:
    - libgc-dev
    - libgmp-dev
    - libgtk-3-dev
    - libev-dev
    - libjson0-dev
    - libjansson-dev
before_install:
  - date
  - cat /proc/cpuinfo
  # Install pkgs
  - ${TRAVIS_BUILD_DIR}/travis-ci/installpkg.sh
  - cd ${HOME}
  # Download ATS2
  - git clone git://git.code.sf.net/p/ats2-lang/code ATS2-srcfrg
  # Seting-up ATS2-contrib
  - export PATSHOMERELOC=${TRAVIS_BUILD_DIR}
script:
  # Building ATS2
  - export PATSHOME=${HOME}/ATS2-srcfrg
  - export PATH=${PATH}:${PATSHOME}/bin
  - (cd ${PATSHOME} && ./configure && make all)
  - export PATH=${HOME}/bin:${PATH}
  # Testing extensively
  - cd ${TRAVIS_BUILD_DIR}
  - make -f Makefile_test testall
after_script:
  - date
